services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: taskflow-app:frontend-${APP_VERSION:-latest}
    container_name: ${FRONTEND_CONTAINER_NAME}
    restart: always
    networks:
      - taskflow_net
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: taskflow-app:backend-${APP_VERSION:-latest}
    container_name: ${BACKEND_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "3003:3003"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - taskflow_net
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./db/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    restart: unless-stopped
    networks:
      - taskflow_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  pgAdmin:
    depends_on:
      db:
        condition: service_healthy
    image: dpage/pgadmin4:9.10
    container_name: ${PGADMIN_CONTAINER_NAME}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - taskflow_net

networks:
  taskflow_net:
    name: ${TASKFLOW_NETWORK_NAME}
    driver: bridge

volumes:
  pgdata:
    name: ${DB_VOLUME_NAME}
  pgadmin:
    name: ${PGADMIN_VOLUME_NAME}
