global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    scrape_interval: 15s
    static_configs:
      - targets: ['backend:3003']
    metrics_path: '/metrics'

